# Generated by Django 5.0.4 on 2024-05-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Chaine')),
                ('visuel', models.CharField(max_length=500, verbose_name='Visuel')),
            ],
            options={
                'verbose_name': 'Chaine',
                'verbose_name_plural': 'Chaines',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Début')),
                ('stop', models.DateTimeField(verbose_name='Fin')),
                ('date', models.DateField(verbose_name='Date')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('visuel', models.CharField(max_length=500, verbose_name='Visuel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Programme_Channel', to='omtv.channel')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['channel', 'start'],
            },
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('channel', 'start'), name='unique_programme_key'),
        ),
    ]
