# Generated by Django 5.0.4 on 2024-05-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['start', 'channel'], 'verbose_name': 'Programme', 'verbose_name_plural': 'Programmes'},
        ),
    ]
