# Generated by Django 5.0.4 on 2024-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='json_datas',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='json_status',
            field=models.IntegerField(default=0, verbose_name='Json Status'),
        ),
    ]
