# Generated by Django 5.0.4 on 2024-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0002_programme_json_datas_programme_json_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='json_datas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
