# Generated by Django 5.0.4 on 2024-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0002_alter_programme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['sort'], 'verbose_name': 'Chaine', 'verbose_name_plural': 'Chaines'},
        ),
        migrations.AddField(
            model_name='channel',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Tri'),
        ),
    ]
