# Generated by Django 5.0.4 on 2024-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0003_alter_programme_json_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='deleted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deleted'),
        ),
    ]
