# Generated by Django 5.0.4 on 2024-05-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0003_alter_channel_options_channel_sort'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programme',
            name='unique_programme_key',
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('start', 'channel'), name='unique_programme_key'),
        ),
    ]
