# Generated by Django 5.0.4 on 2024-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0004_import_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='max_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Max Start'),
        ),
        migrations.AddField(
            model_name='import',
            name='min_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Min Start'),
        ),
    ]
