# Generated by Django 5.0.4 on 2024-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0005_rename_date_programme_pdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('start', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Début')),
                ('end', models.DateTimeField(verbose_name='Fin')),
                ('count_before', models.IntegerField(verbose_name='Count avant')),
                ('count_after', models.IntegerField(verbose_name='Count après')),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Imports',
                'ordering': ['-start'],
            },
        ),
    ]
