# Generated by Django 5.0.4 on 2024-05-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omtv', '0006_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='count_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count après'),
        ),
        migrations.AlterField(
            model_name='import',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin'),
        ),
    ]
